### PR TITLE
mi-temperature plugin added

### PR DESCRIPTION
**Pull request by zuvielx9**

### CODE REVIEW

**Comment by AlCalzone** [comment]
Thanks! Did you only edit the `build/.../*.js` files or are there TypeScript sources?

**Comment by zuvielx9** [comment]
Yes, sorry im beginners in it.

**Comment by AlCalzone** [comment]
No problem! I said I'd make it fit ;)

**Comment by AlCalzone** [comment]
I want to gradually add component tests to all of my adapters. Can you provide some sample data from your sensor along with the expected values from your sensor? The data should include all possible types of messages being sent.

**Comment by AlCalzone** [comment]
I converted your code to TypeScript and put it in the testing branch (dev). Can you please install the adapter from https://github.com/AlCalzone/ioBroker.ble/tarball/dev and test if it still works for you?

**Pull request merged**
